/// Flutter icons FacebookCustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FacebookCustomIcon
///      fonts:
///       - asset: fonts/FacebookCustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FacebookCustomIcon {
  FacebookCustomIcon._();

  static const _kFontFam = 'FacebookCustomIcon';
  static const _kFontPkg = null;

  static const IconData facebook_logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
